name: Generate Snake Animation

on:
  schedule:
    - cron: '0 */6 * * *' # Executa a cada 6 horas
  workflow_dispatch: # Permite executar o workflow manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Grolla05
          outputs: output/github-contribution-grid-snake.svg
          colorscheme: github-dark # Você pode escolher outros temas

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'output/github-contribution-grid-snake.svg'
          message: 'Atualiza a animação da cobra'
          signoff: false
